### ISSUE TITLE
Site unreachable after installation

### ISSUE THREAD

**Issue by aleko21** [eLearning-BS23/moodle-quizaccess_proctoring#35] opened 2021-08-25 07:52 UTC
I attempted to install through the zip file but after uploading my site becomes unreachable. What could be the problem ?

**Comment by ndunand** [comment] 2021-08-25 08:07
I noticed an error upon installation too, debugging message indicating a missing `vendor/autoload.php` .

I fixed it by running the following command in the plugin installation directory:

`composer require async-aws/rekognition`

Maybe this should be added to the README file. Also I could not find any documentation about this "new" dependency on AWS.

**Comment by aleko21** [comment] 2021-08-25 08:14
I'm on shared hosting so i can't run custom commands.

**Comment by AhnafMuttaki** [comment] 2021-08-25 11:14
the issue is fixed now.

**Closed by AhnafMuttaki** 2021-08-25 11:14 UTC
